"""Add primary key ID to PatchDataModel

Revision ID: b34b4379daf6
Revises: 72eec3ed22d0
Create Date: 2025-10-12 16:08:18.315580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b34b4379daf6'
down_revision = '72eec3ed22d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patch_data_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.alter_column('sugar',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('potassium',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user_model', ['owner_id'], ['id'])
        batch_op.drop_column('patch_id')

    with op.batch_alter_table('prediction_history_model', schema=None) as batch_op:
        batch_op.alter_column('prediction_result',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_history_model', schema=None) as batch_op:
        batch_op.alter_column('prediction_result',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('patch_data_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patch_id', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('potassium',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('sugar',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('owner_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
