"""Initial migration for PostgreSQL

Revision ID: 40946a5b22fc
Revises: 
Create Date: 2025-08-01 20:43:44.436111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40946a5b22fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patch_data_model',
    sa.Column('patch_id', sa.String(length=80), nullable=False),
    sa.Column('sugar', sa.Integer(), nullable=False),
    sa.Column('potassium', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('patch_id')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('prediction_history_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prediction_result', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Float(), nullable=False),
    sa.Column('sugar', sa.Integer(), nullable=False),
    sa.Column('potassium', sa.Float(), nullable=False),
    sa.Column('hypertension', sa.Boolean(), nullable=False),
    sa.Column('diabetes_mellitus', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_history_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_history_model_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_history_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_history_model_timestamp'))

    op.drop_table('prediction_history_model')
    op.drop_table('user_model')
    op.drop_table('patch_data_model')
    # ### end Alembic commands ###
